name: Content Management Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Start Docker
            sudo systemctl start docker

            # Navigate to deployment folder
            DEPLOY_DIR="/home/ec2-user/frontend"
            mkdir -p $DEPLOY_DIR
            cd $DEPLOY_DIR

            # Pull latest code
            if [ -d ".git" ]; then
              git reset --hard
              git pull origin main
            else
              git clone https://github.com/BharatVikas/Content-Management-Frontend.git .
            fi

            # Stop & remove any existing container
            if sudo docker ps -a --format '{{.Names}}' | grep -Eq '^frontend-app$'; then
              sudo docker stop frontend-app
              sudo docker rm frontend-app
            fi

            # Remove old image if exists
            if sudo docker images -q frontend-app > /dev/null; then
              sudo docker rmi frontend-app || true
            fi

            # Build new Docker image
            sudo docker build -t frontend-app .

            # Free port 80 if already used
            sudo fuser -k 80/tcp || true

            # Run new container
            sudo docker run -d -p 80:80 --name frontend-app frontend-app
